source 'https://ruby.taobao.org'
#source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'pg'
gem 'devise'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'bootstrap-material-design'
gem 'qiniu'
gem 'whenever'
gem 'public_activity'
gem 'rqrcode_png'
gem 'rails-i18n','4.0.3'
gem 'social-share-button', git: 'git@github.com:apprentice1988/social-share-button.git'
#gem 'memcached'
#gem 'dalli'
gem 'maildown'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'mina'
end

group :development, :test do
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'quiet_assets'
  gem 'minitest-rails'
  gem 'fabrication'
  gem 'byebug'
end
